import {
  CalendarClearTrigger,
  CalendarContext,
  CalendarControl,
  CalendarLabel,
  CalendarMonthSelect,
  CalendarNextTrigger,
  CalendarPresetTrigger,
  CalendarPrevTrigger,
  CalendarRoot,
  CalendarTable,
  CalendarTableBody,
  CalendarTableCell,
  CalendarTableDays,
  CalendarTableHead,
  CalendarTableHeader,
  CalendarTableNextMonth,
  CalendarTableRow,
  CalendarTodayTrigger,
  CalendarTrigger,
  CalendarView,
  CalendarViewControl,
  CalendarViewDate,
  CalendarYearSelect,
  parseDate,
} from "./calendar";

export type { CalendarProps } from "./calendar";
export {
  CalendarClearTrigger,
  CalendarContext,
  CalendarControl,
  CalendarLabel,
  CalendarMonthSelect,
  CalendarNextTrigger,
  CalendarPresetTrigger,
  CalendarPrevTrigger,
  CalendarRoot,
  CalendarTable,
  CalendarTableBody,
  CalendarTableCell,
  CalendarTableDays,
  CalendarTableHead,
  CalendarTableHeader,
  CalendarTableNextMonth,
  CalendarTableRow,
  CalendarTodayTrigger,
  CalendarTrigger,
  CalendarView,
  CalendarViewControl,
  CalendarViewDate,
  CalendarYearSelect,
  parseDate,
};

export const Calendar = Object.assign(CalendarRoot, {
  ClearTrigger: CalendarClearTrigger,
  Context: CalendarContext,
  Control: CalendarControl,
  Label: CalendarLabel,
  MonthSelect: CalendarMonthSelect,
  NextTrigger: CalendarNextTrigger,
  PresetTrigger: CalendarPresetTrigger,
  PrevTrigger: CalendarPrevTrigger,
  Table: CalendarTable,
  TableBody: CalendarTableBody,
  TableCell: CalendarTableCell,
  TableDays: CalendarTableDays,
  TableHead: CalendarTableHead,
  TableHeader: CalendarTableHeader,
  TableNextMonth: CalendarTableNextMonth,
  TableRow: CalendarTableRow,
  TodayTrigger: CalendarTodayTrigger,
  Trigger: CalendarTrigger,
  View: CalendarView,
  ViewControl: CalendarViewControl,
  ViewDate: CalendarViewDate,
  YearSelect: CalendarYearSelect,
});
