import {
  CalendarClearTrigger,
  CalendarContext,
  CalendarControl,
  CalendarLabel,
  CalendarMonthSelect,
  CalendarNextTrigger,
  CalendarPresetTrigger,
  CalendarPrevTrigger,
  CalendarRoot,
  CalendarTable,
  CalendarTableBody,
  CalendarTableCell,
  CalendarTableDays,
  CalendarTableHead,
  CalendarTableHeader,
  CalendarTableNextMonth,
  CalendarTableRow,
  CalendarTodayTrigger,
  CalendarTrigger,
  CalendarView,
  CalendarViewControl,
  CalendarViewDate,
  CalendarWeekDays,
  CalendarYearSelect,
} from "./calendar";

export type {
  CalendarClearTriggerProps,
  CalendarContextProps,
  CalendarControlProps,
  CalendarLabelProps,
  CalendarMonthSelectProps,
  CalendarNextTriggerProps,
  CalendarPresetTriggerProps,
  CalendarPrevTriggerProps,
  CalendarProps,
  CalendarRootProps,
  CalendarTableBodyProps,
  CalendarTableCellProps,
  CalendarTableHeaderProps,
  CalendarTableHeadProps,
  CalendarTableNextMonthProps,
  CalendarTableProps,
  CalendarTableRowProps,
  CalendarTriggerProps,
  CalendarViewControlProps,
  CalendarViewDateProps,
  CalendarViewProps,
  CalendarWeekDaysProps,
  CalendarYearSelectProps,
} from "./calendar";
export { parseDate } from "./calendar";

export const Calendar = Object.assign(CalendarRoot, {
  ClearTrigger: CalendarClearTrigger,
  Context: CalendarContext,
  Control: CalendarControl,
  Label: CalendarLabel,
  MonthSelect: CalendarMonthSelect,
  NextTrigger: CalendarNextTrigger,
  PresetTrigger: CalendarPresetTrigger,
  PrevTrigger: CalendarPrevTrigger,
  Table: CalendarTable,
  TableBody: CalendarTableBody,
  TableCell: CalendarTableCell,
  TableDays: CalendarTableDays,
  TableHead: CalendarTableHead,
  TableHeader: CalendarTableHeader,
  TableNextMonth: CalendarTableNextMonth,
  TableRow: CalendarTableRow,
  TodayTrigger: CalendarTodayTrigger,
  Trigger: CalendarTrigger,
  View: CalendarView,
  ViewControl: CalendarViewControl,
  ViewDate: CalendarViewDate,
  WeekDays: CalendarWeekDays,
  YearSelect: CalendarYearSelect,
});
