import {
  TourActions,
  TourActionTrigger,
  TourBackdrop,
  TourBody,
  TourCloseTrigger,
  TourContent,
  TourDescription,
  TourFooter,
  TourHeader,
  TourNextStep,
  TourPositioner,
  TourPreviousStep,
  TourProgressText,
  TourRoot,
  TourSpotlight,
  TourTitle,
  TourTrigger,
  useTourContext,
} from "./tour";

export type { TourRootProps, TourStepType } from "./tour";
export {
  TourActions,
  TourActionTrigger,
  TourBackdrop,
  TourBody,
  TourCloseTrigger,
  TourContent,
  TourDescription,
  TourFooter,
  TourHeader,
  TourNextStep,
  TourPositioner,
  TourPreviousStep,
  TourProgressText,
  TourRoot,
  TourSpotlight,
  TourTitle,
  TourTrigger,
  useTourContext,
};

export const Tour = Object.assign(TourRoot, {
  Actions: TourActions,
  ActionTrigger: TourActionTrigger,
  Backdrop: TourBackdrop,
  Body: TourBody,
  CloseTrigger: TourCloseTrigger,
  Content: TourContent,
  Description: TourDescription,
  Footer: TourFooter,
  Header: TourHeader,
  NextStep: TourNextStep,
  Positioner: TourPositioner,
  PreviousStep: TourPreviousStep,
  ProgressText: TourProgressText,
  Spotlight: TourSpotlight,
  Title: TourTitle,
  Trigger: TourTrigger,
});
