import {
  ColorPickerArea,
  ColorPickerAreaThumb,
  ColorPickerChannelSlider,
  ColorPickerClearTrigger,
  ColorPickerContent,
  ColorPickerControl,
  ColorPickerEyeDropperTrigger,
  ColorPickerField,
  ColorPickerInput,
  ColorPickerRoot,
  ColorPickerSwatch,
  ColorPickerSwatchGroup,
  ColorPickerSwatchIndicator,
  ColorPickerSwatchPreview,
  ColorPickerSwatchTrigger,
  ColorPickerTransparencyGrid,
  ColorPickerTrigger,
  ColorPickerValueSwatch,
  ColorPickerValueText,
  ColorPickerView,
} from "./color-picker";

export type {
  ColorPickerAreaThumbProps,
  ColorPickerChannelInputProps,
  ColorPickerContentProps,
  ColorPickerSwatchGroupProps,
  ColorPickerSwatchProps,
  ColorPickerTriggerProps,
  ColorPickerValueSwatchProps,
  ColorPickerValueTextProps,
  ColorPickerViewProps,
} from "@ark-ui/react/color-picker";

export type {
  ColorPickerAreaProps,
  ColorPickerChannelSliderProps,
  ColorPickerClearTriggerProps,
  ColorPickerControlProps,
  ColorPickerEyeDropperTriggerProps,
  ColorPickerInputProps,
  ColorPickerProps,
  ColorPickerRootProps,
  ColorPickerSwatchIndicatorProps,
  ColorPickerSwatchPreviewProps,
  ColorPickerSwatchTriggerProps,
  ColorPickerTransparencyGridProps,
} from "./color-picker";
export { parseColor } from "./color-picker";

export const ColorPicker = Object.assign(ColorPickerRoot, {
  Area: ColorPickerArea,
  AreaThumb: ColorPickerAreaThumb,
  ChannelSlider: ColorPickerChannelSlider,
  ClearTrigger: ColorPickerClearTrigger,
  Content: ColorPickerContent,
  Control: ColorPickerControl,
  EyeDropperTrigger: ColorPickerEyeDropperTrigger,
  Field: ColorPickerField,
  Input: ColorPickerInput,
  Swatch: ColorPickerSwatch,
  SwatchGroup: ColorPickerSwatchGroup,
  SwatchIndicator: ColorPickerSwatchIndicator,
  SwatchPreview: ColorPickerSwatchPreview,
  SwatchTrigger: ColorPickerSwatchTrigger,
  TransparencyGrid: ColorPickerTransparencyGrid,
  Trigger: ColorPickerTrigger,
  ValueSwatch: ColorPickerValueSwatch,
  ValueText: ColorPickerValueText,
  View: ColorPickerView,
});
