/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props AccordionProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/accordion` (native HTML attributes omitted). */
export const accordionProps: PropRow[] = [
  {
    defaultValue: "`false`",
    description: "Allow more than one item open.",
    name: "multiple",
    type: "boolean | undefined",
  },
  {
    defaultValue: "`true`",
    description: "Allow closing the open item in single mode.",
    name: "collapsible",
    type: "boolean | undefined",
  },
  {
    defaultValue: "`false`",
    description: "Disable the accordion.",
    name: "disabled",
    type: "boolean | undefined",
  },
];
