/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ActionBarProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/action-bar` (native HTML attributes omitted). */
export const actionBarProps: PropRow[] = [
  {
    defaultValue: "`bottom`",
    description: "Preferred placement.",
    name: "placement",
    type: '"bottom" | "bottom-end" | "bottom-start" | undefined',
  },
  {
    defaultValue: "actionBarRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ActionBarRecipeFn | undefined",
  },
];
