/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props AlertDialogProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/alert-dialog` (native HTML attributes omitted). */
export const alertDialogProps: PropRow[] = [
  {
    defaultValue: "`md`",
    description: "Control size.",
    name: "size",
    type: '"2xl" | "3xl" | "4xl" | "5xl" | "6xl" | "fullscreen" | "lg" | "md" | "sm" | "xl" | undefined',
  },
  {
    defaultValue: "dialogRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "DialogRecipeFn | undefined",
  },
];
