/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props AlertProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/alert` (native HTML attributes omitted). */
export const alertProps: PropRow[] = [
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "destructive" | "info" | "success" | "warning" | undefined',
  },
  {
    defaultValue: "alertRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "AlertRecipeFn | undefined",
  },
];
