/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props AnnouncementProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/announcement` (native HTML attributes omitted). */
export const announcementProps: PropRow[] = [
  {
    defaultValue: "announcementRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "AnnouncementRecipeFn | undefined",
  },
];
