/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props AppShellProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/app-shell` (native HTML attributes omitted). */
export const appShellProps: PropRow[] = [
  {
    defaultValue: "appShellRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "AppShellRecipeFn | undefined",
  },
];
