/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props AspectRatioProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/aspect-ratio` (native HTML attributes omitted). */
export const aspectRatioProps: PropRow[] = [
  {
    defaultValue: "aspectRatioRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "AspectRatioRecipeFn | undefined",
  },
];
