/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props AvatarProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/avatar` (native HTML attributes omitted). */
export const avatarProps: PropRow[] = [
  {
    defaultValue: "`circle`",
    description: "Shape of the control.",
    name: "shape",
    type: '"circle" | "rounded" | "square" | undefined',
  },
  {
    defaultValue: "`md`",
    description: "Control size.",
    name: "size",
    type: '"lg" | "md" | "sm" | undefined',
  },
  {
    defaultValue: "avatarRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "AvatarRecipeFn | undefined",
  },
];
