/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props BadgeProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/badge` (native HTML attributes omitted). */
export const badgeProps: PropRow[] = [
  {
    defaultValue: "`false`",
    description: "Fully rounded corners.",
    name: "pill",
    type: '"true" | "sm" | undefined',
  },
  {
    defaultValue: "`md`",
    description: "Control size.",
    name: "size",
    type: '"lg" | "md" | "sm" | undefined',
  },
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "focus-visible" | "focus-visible" | "dark" | "focus-visible" | "hover" | "destructive" | "dark" | "focus-visible" | "focus-visible" | "dark" | "focus-visible" | "hover" | "info" | "focus-visible" | "focus-visible" | "hover" | "outline" | "hover" | "hover" | "secondary" | "focus-visible" | "focus-visible" | "hover" | "success" | "focus-visible" | "focus-visible" | "hover" | "warning" | "focus-visible" | "focus-visible" | "dark" | "focus-visible" | "hover" | undefined',
  },
  {
    defaultValue: "badgeRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "BadgeRecipeFn | undefined",
  },
];
