/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props BottomNavigationProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/bottom-navigation` (native HTML attributes omitted). */
export const bottomNavigationProps: PropRow[] = [
  {
    defaultValue: "bottomNavigationRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "BottomNavigationRecipeFn | undefined",
  },
];
