/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props BreadcrumbProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/breadcrumb` (native HTML attributes omitted). */
export const breadcrumbProps: PropRow[] = [
  {
    defaultValue: "breadcrumbRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "BreadcrumbRecipeFn | undefined",
  },
];
