/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ButtonProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/button` (native HTML attributes omitted). */
export const buttonProps: PropRow[] = [
  {
    defaultValue: "`true`",
    description: "Scale feedback on press.",
    name: "clickEffect",
    type: "boolean | undefined",
  },
  {
    defaultValue: "`false`",
    description: "Shows a spinner and disables interaction.",
    name: "loading",
    type: "boolean | undefined",
  },
  {
    defaultValue: "`false`",
    description: "Fully rounded corners.",
    name: "pill",
    type: "boolean | undefined",
  },
  {
    defaultValue: "`md`",
    description: "Control height and padding, or square icon sizes.",
    name: "size",
    type: '"icon-lg" | "icon-md" | "icon-sm" | "icon-xl" | "icon-xs" | "lg" | "md" | "sm" | "xl" | "xs" | undefined',
  },
  {
    defaultValue: "`default`",
    description: "Visual emphasis of the button.",
    name: "variant",
    type: '"default" | "destructive" | "ghost" | "link" | "outline" | "secondary" | undefined',
  },
  {
    defaultValue: "buttonRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ButtonRecipeFn | undefined",
  },
];
