/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ButtonGroupProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/button-group` (native HTML attributes omitted). */
export const buttonGroupProps: PropRow[] = [
  {
    defaultValue: "`horizontal`",
    description: "Layout orientation.",
    name: "orientation",
    type: '"horizontal" | "vertical" | undefined',
  },
  {
    defaultValue: "buttonGroupRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ButtonGroupRecipeFn | undefined",
  },
];
