/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props CalendarProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/calendar` (native HTML attributes omitted). */
export const calendarProps: PropRow[] = [
  {
    defaultValue: "calendarRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "CalendarRecipeFn | undefined",
  },
];
