/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props CardProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/card` (native HTML attributes omitted). */
export const cardProps: PropRow[] = [
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "icon" | "image" | undefined',
  },
  {
    defaultValue: "cardRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "CardRecipeFn | undefined",
  },
];
