/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props CarouselProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/carousel` (native HTML attributes omitted). */
export const carouselProps: PropRow[] = [
  {
    defaultValue: "carouselRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "CarouselRecipeFn | undefined",
  },
];
