/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ChartProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/chart` (native HTML attributes omitted). */
export const chartProps: PropRow[] = [
  {
    defaultValue: "chartRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ChartRecipeFn | undefined",
  },
];
