/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props CircularProgressProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/circular-progress` (native HTML attributes omitted). */
export const circularProgressProps: PropRow[] = [
  {
    defaultValue: "circularProgressRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "CircularProgressRecipeFn | undefined",
  },
];
