/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ClipboardProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/clipboard` (native HTML attributes omitted). */
export const clipboardProps: PropRow[] = [
  {
    defaultValue: "`md`",
    description: "Value size.",
    name: "valueSize",
    type: '"lg" | "md" | "sm" | "xl" | "xs" | undefined',
  },
  {
    defaultValue: "clipboardRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ClipboardRecipeFn | undefined",
  },
];
