/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props CollapsibleProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/collapsible` (native HTML attributes omitted). */
export const collapsibleProps: PropRow[] = [
  {
    defaultValue: "collapsibleRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "CollapsibleRecipeFn | undefined",
  },
];
