/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ColorPickerProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/color-picker` (native HTML attributes omitted). */
export const colorPickerProps: PropRow[] = [
  {
    defaultValue: "colorPickerRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ColorPickerRecipeFn | undefined",
  },
];
