/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ComboboxProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/combobox` (native HTML attributes omitted). */
export const comboboxProps: PropRow[] = [
  {
    defaultValue: "`true`",
    description: "Show indicator.",
    name: "showIndicator",
    type: "boolean | undefined",
  },
  {
    defaultValue: "comboboxRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ComboboxRecipeFn | undefined",
  },
];
