/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ContextMenuProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/context-menu` (native HTML attributes omitted). */
export const contextMenuProps: PropRow[] = [
  {
    defaultValue: "contextMenuRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ContextMenuRecipeFn | undefined",
  },
];
