/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props DataTableProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/data-table` (native HTML attributes omitted). */
export const dataTableProps: PropRow[] = [
  {
    defaultValue: "dataTableRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "DataTableRecipeFn | undefined",
  },
];
