/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props DataGridProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/data-grid` (native HTML attributes omitted). */
export const dataGridProps: PropRow[] = [
  {
    defaultValue: "dataGridRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "DataGridRecipeFn | undefined",
  },
];
