/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props DataListProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/data-list` (native HTML attributes omitted). */
export const dataListProps: PropRow[] = [
  {
    defaultValue: "dataListRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "DataListRecipeFn | undefined",
  },
];
