/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props DatePickerProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/date-picker` (native HTML attributes omitted). */
export const datePickerProps: PropRow[] = [
  {
    defaultValue: "datePickerRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "DatePickerRecipeFn | undefined",
  },
];
