/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props DrawerProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/drawer` (native HTML attributes omitted). */
export const drawerProps: PropRow[] = [
  {
    defaultValue: "`down`",
    description: "Preferred placement.",
    name: "placement",
    type: '"down" | "left" | "right" | "up" | undefined',
  },
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "inset" | undefined',
  },
  {
    defaultValue: "drawerRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "DrawerRecipeFn | undefined",
  },
];
