/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props DropdownMenuProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/dropdown-menu` (native HTML attributes omitted). */
export const dropdownMenuProps: PropRow[] = [
  {
    defaultValue: "dropdownMenuRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "DropdownMenuRecipeFn | undefined",
  },
];
