/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props EmptyStateProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/empty-state` (native HTML attributes omitted). */
export const emptyStateProps: PropRow[] = [
  {
    defaultValue: "emptyStateRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "EmptyStateRecipeFn | undefined",
  },
];
