/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props FieldProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/field` (native HTML attributes omitted). */
export const fieldProps: PropRow[] = [
  {
    defaultValue: "`vertical`",
    description: "Layout orientation.",
    name: "orientation",
    type: '"horizontal" | "responsive" | "vertical" | undefined',
  },
  {
    defaultValue: "`false`",
    description: "Reverse.",
    name: "reverse",
    type: "boolean | undefined",
  },
  {
    defaultValue: "fieldRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "FieldRecipeFn | undefined",
  },
];
