/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props FileInputProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/file-input` (native HTML attributes omitted). */
export const fileInputProps: PropRow[] = [
  {
    defaultValue: "fileInputRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "FileInputRecipeFn | undefined",
  },
];
