/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props FileProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/file` (native HTML attributes omitted). */
export const fileProps: PropRow[] = [
  {
    defaultValue: "`icon`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"icon" | "image" | undefined',
  },
  {
    defaultValue: "fileRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "FileRecipeFn | undefined",
  },
];
