/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props FloatingPanelProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/floating-panel` (native HTML attributes omitted). */
export const floatingPanelProps: PropRow[] = [
  {
    defaultValue: "floatingPanelRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "FloatingPanelRecipeFn | undefined",
  },
];
