/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props FormControlShellProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/form-control` (native HTML attributes omitted). */
export const formControlProps: PropRow[] = [
  {
    defaultValue: "`md`",
    description: "Control size.",
    name: "size",
    type: '"lg" | "md" | "sm" | undefined',
  },
  {
    defaultValue: "undefined",
    description: "Surface variant.",
    name: "surfaceVariant",
    type: "unknown",
  },
  {
    defaultValue: "`primary`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"primary" | "secondary" | undefined',
  },
  {
    defaultValue: "formControlShellRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "FormControlShellRecipeFn | undefined",
  },
];
