/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props FrameProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/frame` (native HTML attributes omitted). */
export const frameProps: PropRow[] = [
  {
    defaultValue: "frameRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "FrameRecipeFn | undefined",
  },
];
