/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props HighlightProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/highlight` (native HTML attributes omitted). */
export const highlightProps: PropRow[] = [
  {
    defaultValue: "highlightRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "HighlightRecipeFn | undefined",
  },
];
