/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ImageCropperProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/image-cropper` (native HTML attributes omitted). */
export const imageCropperProps: PropRow[] = [
  {
    defaultValue: "imageCropperRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ImageCropperRecipeFn | undefined",
  },
];
