/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props InputProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/input` (native HTML attributes omitted). */
export const inputProps: PropRow[] = [
  {
    defaultValue: "inputRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "InputRecipeFn | undefined",
  },
];
