/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props InputOtpProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/input-otp` (native HTML attributes omitted). */
export const inputOtpProps: PropRow[] = [
  {
    defaultValue: "inputOtpRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "InputOtpRecipeFn | undefined",
  },
];
