/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props InputGroupAddonProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/input-group` (native HTML attributes omitted). */
export const inputGroupProps: PropRow[] = [
  {
    defaultValue: "`inline-start`",
    description: "Alignment along the cross axis.",
    name: "align",
    type: '"block-end" | "input-group" | "block-start" | "input-group" | "inline-end" | "inline-start" | undefined',
  },
  {
    defaultValue: "inputGroupAddonRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "InputGroupAddonRecipeFn | undefined",
  },
];
