/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ItemProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/item` (native HTML attributes omitted). */
export const itemProps: PropRow[] = [
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "icon" | "image" | "muted" | "outline" | undefined',
  },
  {
    defaultValue: "itemRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ItemRecipeFn | undefined",
  },
];
