/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props JsonTreeViewProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/json-tree-view` (native HTML attributes omitted). */
export const jsonTreeViewProps: PropRow[] = [
  {
    defaultValue: "jsonTreeViewRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "JsonTreeViewRecipeFn | undefined",
  },
];
