/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props KbdProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/kbd` (native HTML attributes omitted). */
export const kbdProps: PropRow[] = [
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "outline" | undefined',
  },
  {
    defaultValue: "kbdRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "KbdRecipeFn | undefined",
  },
];
