/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props LinkBoxProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/link-box` (native HTML attributes omitted). */
export const linkBoxProps: PropRow[] = [
  {
    defaultValue: "linkBoxRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "LinkBoxRecipeFn | undefined",
  },
];
