/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ListboxProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/listbox` (native HTML attributes omitted). */
export const listboxProps: PropRow[] = [
  {
    defaultValue: "listboxRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ListboxRecipeFn | undefined",
  },
];
