/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props MarqueeProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/marquee` (native HTML attributes omitted). */
export const marqueeProps: PropRow[] = [
  {
    defaultValue: "marqueeRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "MarqueeRecipeFn | undefined",
  },
];
