/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props MenuProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/menu` (native HTML attributes omitted). */
export const menuProps: PropRow[] = [
  {
    defaultValue: "menuRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "MenuRecipeFn | undefined",
  },
];
