/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props NavbarProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/navbar` (native HTML attributes omitted). */
export const navbarProps: PropRow[] = [
  {
    defaultValue: "navbarRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "NavbarRecipeFn | undefined",
  },
];
