/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props NavigationMenuProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/navigation-menu` (native HTML attributes omitted). */
export const navigationMenuProps: PropRow[] = [
  {
    defaultValue: "navigationMenuRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "NavigationMenuRecipeFn | undefined",
  },
];
