/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props NumberInputProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/number-input` (native HTML attributes omitted). */
export const numberInputProps: PropRow[] = [
  {
    defaultValue: "numberInputRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "NumberInputRecipeFn | undefined",
  },
];
