/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props PasswordInputProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/password-input` (native HTML attributes omitted). */
export const passwordInputProps: PropRow[] = [
  {
    defaultValue: "passwordInputRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "PasswordInputRecipeFn | undefined",
  },
];
