/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props PhoneInputProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/phone-input` (native HTML attributes omitted). */
export const phoneInputProps: PropRow[] = [
  {
    defaultValue: "`md`",
    description: "Control size.",
    name: "size",
    type: '"lg" | "md" | "sm" | undefined',
  },
  {
    defaultValue: "phoneInputRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "PhoneInputRecipeFn | undefined",
  },
];
