/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props PopoverProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/popover` (native HTML attributes omitted). */
export const popoverProps: PropRow[] = [
  {
    defaultValue: "popoverRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "PopoverRecipeFn | undefined",
  },
];
