/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ProgressProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/progress` (native HTML attributes omitted). */
export const progressProps: PropRow[] = [
  {
    defaultValue: "progressRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ProgressRecipeFn | undefined",
  },
];
