/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ProseProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/prose` (native HTML attributes omitted). */
export const proseProps: PropRow[] = [
  {
    defaultValue: "proseRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ProseRecipeFn | undefined",
  },
];
