/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props QrCodeProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/qr-code` (native HTML attributes omitted). */
export const qrCodeProps: PropRow[] = [
  {
    defaultValue: "qrCodeRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "QrCodeRecipeFn | undefined",
  },
];
