/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props RadioGroupProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/radio-group` (native HTML attributes omitted). */
export const radioGroupProps: PropRow[] = [
  {
    defaultValue: "radioGroupRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "RadioGroupRecipeFn | undefined",
  },
];
