/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ResizableProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/resizable` (native HTML attributes omitted). */
export const resizableProps: PropRow[] = [
  {
    defaultValue: "resizableRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ResizableRecipeFn | undefined",
  },
];
