/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props RichTextEditorProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/rich-text-editor` (native HTML attributes omitted). */
export const richTextEditorProps: PropRow[] = [
  {
    defaultValue: "richTextEditorRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "RichTextEditorRecipeFn | undefined",
  },
];
