/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ScrollAreaProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/scroll-area` (native HTML attributes omitted). */
export const scrollAreaProps: PropRow[] = [
  {
    defaultValue: "`false`",
    description: "Scroll fade.",
    name: "scrollFade",
    type: "boolean | undefined",
  },
  {
    defaultValue: "scrollAreaRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ScrollAreaRecipeFn | undefined",
  },
];
