/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SegmentGroupProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/segment-group` (native HTML attributes omitted). */
export const segmentGroupProps: PropRow[] = [
  {
    defaultValue: "segmentGroupRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SegmentGroupRecipeFn | undefined",
  },
];
