/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SelectProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/select` (native HTML attributes omitted). */
export const selectProps: PropRow[] = [
  {
    defaultValue: "selectRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SelectRecipeFn | undefined",
  },
];
