/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SeparatorProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/separator` (native HTML attributes omitted). */
export const separatorProps: PropRow[] = [
  {
    defaultValue: "separatorRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SeparatorRecipeFn | undefined",
  },
];
