/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SheetProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/sheet` (native HTML attributes omitted). */
export const sheetProps: PropRow[] = [
  {
    defaultValue: "`right`",
    description: "Preferred placement.",
    name: "placement",
    type: '"bottom" | "left" | "right" | "top" | undefined',
  },
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "inset" | undefined',
  },
  {
    defaultValue: "sheetRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SheetRecipeFn | undefined",
  },
];
