/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SidebarProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/sidebar` (native HTML attributes omitted). */
export const sidebarProps: PropRow[] = [
  {
    defaultValue: "`false`",
    description: "Include inner padding.",
    name: "padded",
    type: "boolean | undefined",
  },
  {
    defaultValue: "`left`",
    description: "Preferred placement.",
    name: "placement",
    type: '"left" | "right" | undefined',
  },
  {
    defaultValue: "sidebarRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SidebarRecipeFn | undefined",
  },
];
