/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SkeletonProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/skeleton` (native HTML attributes omitted). */
export const skeletonProps: PropRow[] = [
  {
    defaultValue: "skeletonRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SkeletonRecipeFn | undefined",
  },
];
