/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SkipNavProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/skip-nav` (native HTML attributes omitted). */
export const skipNavProps: PropRow[] = [
  {
    defaultValue: "skipNavRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SkipNavRecipeFn | undefined",
  },
];
