/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SliderProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/slider` (native HTML attributes omitted). */
export const sliderProps: PropRow[] = [
  {
    defaultValue: "sliderRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SliderRecipeFn | undefined",
  },
];
