/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props StatProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/stat` (native HTML attributes omitted). */
export const statProps: PropRow[] = [
  {
    defaultValue: "`outline`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "muted" | "outline" | undefined',
  },
  {
    defaultValue: "statRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "StatRecipeFn | undefined",
  },
];
