/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props StatusProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/status` (native HTML attributes omitted). */
export const statusProps: PropRow[] = [
  {
    defaultValue: "`md`",
    description: "Control size.",
    name: "size",
    type: '"lg" | "_svg" | "md" | "_svg" | "sm" | "_svg" | undefined',
  },
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "destructive" | "info" | "success" | "warning" | undefined',
  },
  {
    defaultValue: "statusRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "StatusRecipeFn | undefined",
  },
];
