/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props StepsProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/steps` (native HTML attributes omitted). */
export const stepsProps: PropRow[] = [
  {
    defaultValue: "stepsRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "StepsRecipeFn | undefined",
  },
];
