/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SurfaceProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/surface` (native HTML attributes omitted). */
export const surfaceProps: PropRow[] = [
  {
    defaultValue: "`false`",
    description: "Show border.",
    name: "bordered",
    type: "boolean | undefined",
  },
  {
    defaultValue: "`true`",
    description: "Rounded corners.",
    name: "rounded",
    type: "boolean | undefined",
  },
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "glass" | "transparency-reduce" | "transparency-reduce" | "transparency-reduce" | "contrast-more" | "contrast-more" | "secondary" | "tertiary" | "transparent" | undefined',
  },
  {
    defaultValue: "surfaceRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SurfaceRecipeFn | undefined",
  },
];
