/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SwapProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/swap` (native HTML attributes omitted). */
export const swapProps: PropRow[] = [
  {
    defaultValue: "`fade`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"blur" | "fade" | "flip" | "rotate" | "scale" | undefined',
  },
  {
    defaultValue: "swapRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SwapRecipeFn | undefined",
  },
];
