/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props SwitchProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/switch` (native HTML attributes omitted). */
export const switchProps: PropRow[] = [
  {
    defaultValue: "undefined",
    description: "Surface variant.",
    name: "surfaceVariant",
    type: "unknown",
  },
  {
    defaultValue: "`primary`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"primary" | "secondary" | undefined',
  },
  {
    defaultValue: "switchRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "SwitchRecipeFn | undefined",
  },
];
