/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props TabsProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/tabs` (native HTML attributes omitted). */
export const tabsProps: PropRow[] = [
  {
    defaultValue: "`default`",
    description: "Visual emphasis.",
    name: "variant",
    type: '"default" | "underline" | undefined',
  },
  {
    defaultValue: "tabsRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "TabsRecipeFn | undefined",
  },
];
