/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props TagsInputProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/tags-input` (native HTML attributes omitted). */
export const tagsInputProps: PropRow[] = [
  {
    defaultValue: "tagsInputRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "TagsInputRecipeFn | undefined",
  },
];
