/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props TextareaProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/textarea` (native HTML attributes omitted). */
export const textareaProps: PropRow[] = [
  {
    defaultValue: "textareaRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "TextareaRecipeFn | undefined",
  },
];
