/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props TimerProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/timer` (native HTML attributes omitted). */
export const timerProps: PropRow[] = [
  {
    defaultValue: "timerRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "TimerRecipeFn | undefined",
  },
];
