/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props TimelineProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/timeline` (native HTML attributes omitted). */
export const timelineProps: PropRow[] = [
  {
    defaultValue: "`vertical`",
    description: "Layout orientation.",
    name: "orientation",
    type: '"horizontal" | "vertical" | undefined',
  },
  {
    defaultValue: "timelineRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "TimelineRecipeFn | undefined",
  },
];
