/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ToastProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/toast` (native HTML attributes omitted). */
export const toastProps: PropRow[] = [
  {
    defaultValue: "toastRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ToastRecipeFn | undefined",
  },
];
