/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props TooltipProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/tooltip` (native HTML attributes omitted). */
export const tooltipProps: PropRow[] = [
  {
    defaultValue: "tooltipRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "TooltipRecipeFn | undefined",
  },
];
