/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props ToolbarProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/toolbar` (native HTML attributes omitted). */
export const toolbarProps: PropRow[] = [
  {
    defaultValue: "toolbarRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "ToolbarRecipeFn | undefined",
  },
];
