/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props TourProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/tour` (native HTML attributes omitted). */
export const tourProps: PropRow[] = [
  {
    defaultValue: "tourRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "TourRecipeFn | undefined",
  },
];
