/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props TreeViewProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/tree-view` (native HTML attributes omitted). */
export const treeViewProps: PropRow[] = [
  {
    defaultValue: "treeViewRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "TreeViewRecipeFn | undefined",
  },
];
