/* eslint-disable */
// Generated by `bun apps/docs/scripts/generate-props-tables.ts` from @pisagor/props VisuallyHiddenProps. Do not edit.
import type { PropRow } from "./types";

export type { PropRow };

/** Own props from `@pisagor/props/visually-hidden` (native HTML attributes omitted). */
export const visuallyHiddenProps: PropRow[] = [
  {
    defaultValue: "visuallyHiddenRecipe",
    description: "Style recipe override.",
    name: "recipe",
    type: "VisuallyHiddenRecipeFn | undefined",
  },
];
