name: Checks

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Turborepo Remote Cache
        uses: vercel/setup-turborepo-remote-cache-action@v1.1.0
        with:
          team: ${{ vars.TURBO_TEAM }}
      - uses: ./.github/actions/setup-bun
      - run: bunx biome ci
      - run: bunx knip
      - run: bun run type-check
      - run: bun run test
      - run: bun run build
